version: "3.8"

services:
  backend:
    build: ./backend
    container_name: ecommerce-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/data
      - ./backend/ecommerce.db:/app/ecommerce.db
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY:-}
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: ecommerce-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:8000 